version: '3.8'
services:
  api:
    depends_on:
      - db
    build: ./Backend
    ports:
      - 5000:3000
    environment:
      - MONGO_URI=mongodb://db:27017/audiobookdb

  db:
    image: mongo:latest
    ports:
      - 27018:27017
    volumes:
      - audiobook:/data/db
volumes:
  audiobook:
